services:
  n8n-editor:
    image: n8nio/n8n:latest
    container_name: n8n-editor
    restart: always
    ports:
      - 5676:5678
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - common-network
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
  n8n-workers:
    image: n8nio/n8n:latest
    container_name: n8n-workers
    restart: always
    ports:
      - 5677:5678
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - common-network
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: worker
  n8n-webhooks:
    image: n8nio/n8n:latest
    container_name: n8n-webhooks
    restart: always
    ports:
      - 5678:5678
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - common-network
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: webhook
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres-n8n
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: n8n
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - common-network
  redis:
    image: redis:alpine
    container_name: redis-n8n
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - common-network
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-n8n
    restart: always
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
    ports:
      - 15432:80
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - common-network
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-n8n
    restart: always
    volumes:
      - redisinsight-data:/data
    ports:
      - 16379:5540
    depends_on:
      - redis
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  n8n-data:
  redisinsight-data:
  pgadmin4-data:
